//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.LoginParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.UpdateUserParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetUserInfosParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetUsersParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.DeleteUserParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ForgetPasswordParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ActivateKeyParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.RegisterParams))]
    public partial class WSParams : object
    {
        
        private ServiceReference1.AccessParams AccessParamsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AccessParams AccessParams
        {
            get
            {
                return this.AccessParamsField;
            }
            set
            {
                this.AccessParamsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class AccessParams : object
    {
        
        private ServiceReference1.FacebookParams FacebookParamsField;
        
        private ServiceReference1.OAuth2Service OAuth2ServiceField;
        
        private ServiceReference1.OnAirParams OnAirParamsField;
        
        private ServiceReference1.TwitterParams TwitterParamsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.FacebookParams FacebookParams
        {
            get
            {
                return this.FacebookParamsField;
            }
            set
            {
                this.FacebookParamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.OAuth2Service OAuth2Service
        {
            get
            {
                return this.OAuth2ServiceField;
            }
            set
            {
                this.OAuth2ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.OnAirParams OnAirParams
        {
            get
            {
                return this.OnAirParamsField;
            }
            set
            {
                this.OnAirParamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TwitterParams TwitterParams
        {
            get
            {
                return this.TwitterParamsField;
            }
            set
            {
                this.TwitterParamsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class LoginParams : ServiceReference1.WSParams
    {
        
        private System.Guid DirectoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateUserParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class UpdateUserParams : ServiceReference1.WSParams
    {
        
        private System.Guid DirectoryIdField;
        
        private bool IsDirectoryAdminField;
        
        private string NewEmailField;
        
        private string NewFirstNameField;
        
        private string NewLastNameField;
        
        private string NewPasswordField;
        
        private System.Collections.Generic.List<ServiceReference1.WSUserProperty> PropertiesField;
        
        private System.Collections.Generic.List<string> RolesField;
        
        private System.Nullable<System.Guid> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDirectoryAdmin
        {
            get
            {
                return this.IsDirectoryAdminField;
            }
            set
            {
                this.IsDirectoryAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewEmail
        {
            get
            {
                return this.NewEmailField;
            }
            set
            {
                this.NewEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewFirstName
        {
            get
            {
                return this.NewFirstNameField;
            }
            set
            {
                this.NewFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewLastName
        {
            get
            {
                return this.NewLastNameField;
            }
            set
            {
                this.NewLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.WSUserProperty> Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserInfosParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class GetUserInfosParams : ServiceReference1.WSParams
    {
        
        private System.Nullable<System.Guid> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class GetUsersParams : ServiceReference1.WSParams
    {
        
        private System.Guid DirectoryIdField;
        
        private string EmailFilterField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFilter
        {
            get
            {
                return this.EmailFilterField;
            }
            set
            {
                this.EmailFilterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteUserParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class DeleteUserParams : ServiceReference1.WSParams
    {
        
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForgetPasswordParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class ForgetPasswordParams : ServiceReference1.WSParams
    {
        
        private System.Guid DirectoryIdField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivateKeyParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class ActivateKeyParams : ServiceReference1.WSParams
    {
        
        private string KeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class RegisterParams : ServiceReference1.WSParams
    {
        
        private string ActivationKeyField;
        
        private System.Guid DirectoryIdField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PasswordField;
        
        private System.Collections.Generic.List<ServiceReference1.WSUserProperty> PropertiesField;
        
        private string RedirectUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationKey
        {
            get
            {
                return this.ActivationKeyField;
            }
            set
            {
                this.ActivationKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.WSUserProperty> Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedirectUrl
        {
            get
            {
                return this.RedirectUrlField;
            }
            set
            {
                this.RedirectUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSUserProperty", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class WSUserProperty : object
    {
        
        private string NameField;
        
        private System.Nullable<bool> ValueBoolField;
        
        private byte[] ValueBytesField;
        
        private System.Nullable<System.DateTime> ValueDateTimeField;
        
        private System.Nullable<double> ValueDoubleField;
        
        private ServiceReference1.WSUserPropertyFile ValueFileField;
        
        private System.Nullable<int> ValueIntField;
        
        private string ValueStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ValueBool
        {
            get
            {
                return this.ValueBoolField;
            }
            set
            {
                this.ValueBoolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ValueBytes
        {
            get
            {
                return this.ValueBytesField;
            }
            set
            {
                this.ValueBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValueDateTime
        {
            get
            {
                return this.ValueDateTimeField;
            }
            set
            {
                this.ValueDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueDouble
        {
            get
            {
                return this.ValueDoubleField;
            }
            set
            {
                this.ValueDoubleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.WSUserPropertyFile ValueFile
        {
            get
            {
                return this.ValueFileField;
            }
            set
            {
                this.ValueFileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ValueInt
        {
            get
            {
                return this.ValueIntField;
            }
            set
            {
                this.ValueIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueString
        {
            get
            {
                return this.ValueStringField;
            }
            set
            {
                this.ValueStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacebookParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class FacebookParams : object
    {
        
        private string AccessTokenField;
        
        private string FieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fields
        {
            get
            {
                return this.FieldsField;
            }
            set
            {
                this.FieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnAirParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class OnAirParams : object
    {
        
        private string AccessTokenField;
        
        private string EmailField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TwitterParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class TwitterParams : object
    {
        
        private string ConsumerKeyField;
        
        private string ConsumerSecretField;
        
        private string TokenField;
        
        private string TokenSecretField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerKey
        {
            get
            {
                return this.ConsumerKeyField;
            }
            set
            {
                this.ConsumerKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerSecret
        {
            get
            {
                return this.ConsumerSecretField;
            }
            set
            {
                this.ConsumerSecretField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSecret
        {
            get
            {
                return this.TokenSecretField;
            }
            set
            {
                this.TokenSecretField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAuth2Service", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public enum OAuth2Service : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnAir = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facebook = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Google = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Twitter = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSUserPropertyFile", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class WSUserPropertyFile : object
    {
        
        private byte[] BytesField;
        
        private string ExtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes
        {
            get
            {
                return this.BytesField;
            }
            set
            {
                this.BytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ext
        {
            get
            {
                return this.ExtField;
            }
            set
            {
                this.ExtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSResult", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.LoginResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetUserInfosResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetUsersResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetActivatedKeysResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetSubscriptionEndDateResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.RegisterResult))]
    public partial class WSResult : object
    {
        
        private ServiceReference1.Error ErrorField;
        
        private bool IsSuccessField;
        
        private ServiceReference1.OAuth2Service OAuth2ServiceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.OAuth2Service OAuth2Service
        {
            get
            {
                return this.OAuth2ServiceField;
            }
            set
            {
                this.OAuth2ServiceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class Error : object
    {
        
        private ServiceReference1.ErrorCode CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ErrorCode Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class LoginResult : ServiceReference1.WSResult
    {
        
        private ServiceReference1.AccessParams AccessParamsField;
        
        private ServiceReference1.OAuthServiceUserInfos UserInfosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AccessParams AccessParams
        {
            get
            {
                return this.AccessParamsField;
            }
            set
            {
                this.AccessParamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.OAuthServiceUserInfos UserInfos
        {
            get
            {
                return this.UserInfosField;
            }
            set
            {
                this.UserInfosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserInfosResult", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class GetUserInfosResult : ServiceReference1.WSResult
    {
        
        private System.Guid DirectoryIdField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private string LastNameField;
        
        private string OAuth2ServiceUserIdField;
        
        private ServiceReference1.PaypalSubStatus PaypalSubStatusField;
        
        private System.Collections.Generic.List<ServiceReference1.GetUserInfosResult.UserProperty> PropertiesField;
        
        private System.Collections.Generic.List<string> RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OAuth2ServiceUserId
        {
            get
            {
                return this.OAuth2ServiceUserIdField;
            }
            set
            {
                this.OAuth2ServiceUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PaypalSubStatus PaypalSubStatus
        {
            get
            {
                return this.PaypalSubStatusField;
            }
            set
            {
                this.PaypalSubStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.GetUserInfosResult.UserProperty> Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GetUserInfosResult.UserProperty", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
        public partial class UserProperty : object
        {
            
            private string NameField;
            
            private System.Nullable<bool> ValueBoolField;
            
            private byte[] ValueBytesField;
            
            private System.Nullable<System.DateTime> ValueDateTimeField;
            
            private System.Nullable<double> ValueDoubleField;
            
            private string ValueFileField;
            
            private System.Nullable<int> ValueIntField;
            
            private string ValueStringField;
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Name
            {
                get
                {
                    return this.NameField;
                }
                set
                {
                    this.NameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<bool> ValueBool
            {
                get
                {
                    return this.ValueBoolField;
                }
                set
                {
                    this.ValueBoolField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public byte[] ValueBytes
            {
                get
                {
                    return this.ValueBytesField;
                }
                set
                {
                    this.ValueBytesField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<System.DateTime> ValueDateTime
            {
                get
                {
                    return this.ValueDateTimeField;
                }
                set
                {
                    this.ValueDateTimeField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<double> ValueDouble
            {
                get
                {
                    return this.ValueDoubleField;
                }
                set
                {
                    this.ValueDoubleField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ValueFile
            {
                get
                {
                    return this.ValueFileField;
                }
                set
                {
                    this.ValueFileField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<int> ValueInt
            {
                get
                {
                    return this.ValueIntField;
                }
                set
                {
                    this.ValueIntField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ValueString
            {
                get
                {
                    return this.ValueStringField;
                }
                set
                {
                    this.ValueStringField = value;
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersResult", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class GetUsersResult : ServiceReference1.WSResult
    {
        
        private System.Collections.Generic.List<ServiceReference1.GetUsersResult.UserInfos> UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.GetUsersResult.UserInfos> Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersResult.UserInfos", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
        public partial class UserInfos : object
        {
            
            private string EmailField;
            
            private string FirstNameField;
            
            private System.Guid IdField;
            
            private string LastNameField;
            
            private System.Collections.Generic.List<ServiceReference1.GetUserInfosResult.UserProperty> PropertiesField;
            
            private System.Collections.Generic.List<string> RolesField;
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Email
            {
                get
                {
                    return this.EmailField;
                }
                set
                {
                    this.EmailField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FirstName
            {
                get
                {
                    return this.FirstNameField;
                }
                set
                {
                    this.FirstNameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Guid Id
            {
                get
                {
                    return this.IdField;
                }
                set
                {
                    this.IdField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string LastName
            {
                get
                {
                    return this.LastNameField;
                }
                set
                {
                    this.LastNameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Collections.Generic.List<ServiceReference1.GetUserInfosResult.UserProperty> Properties
            {
                get
                {
                    return this.PropertiesField;
                }
                set
                {
                    this.PropertiesField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Collections.Generic.List<string> Roles
            {
                get
                {
                    return this.RolesField;
                }
                set
                {
                    this.RolesField = value;
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetActivatedKeysResult", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class GetActivatedKeysResult : ServiceReference1.WSResult
    {
        
        private System.Collections.Generic.List<ServiceReference1.ActivationKey> KeysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.ActivationKey> Keys
        {
            get
            {
                return this.KeysField;
            }
            set
            {
                this.KeysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSubscriptionEndDateResult", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class GetSubscriptionEndDateResult : ServiceReference1.WSResult
    {
        
        private System.Nullable<System.DateTime> DateField;
        
        private ServiceReference1.PaypalSubStatus PaypalSubStatusField;
        
        private bool SubscriptionActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PaypalSubStatus PaypalSubStatus
        {
            get
            {
                return this.PaypalSubStatusField;
            }
            set
            {
                this.PaypalSubStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SubscriptionActive
        {
            get
            {
                return this.SubscriptionActiveField;
            }
            set
            {
                this.SubscriptionActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterResult", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class RegisterResult : ServiceReference1.WSResult
    {
        
        private bool EmailConfirmedField;
        
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed
        {
            get
            {
                return this.EmailConfirmedField;
            }
            set
            {
                this.EmailConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCode", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public enum ErrorCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailAlreadyExists = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DirectoryDoesNotExist = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadCredentials = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserDoesNotExist = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeyInvalid = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAuthServiceUserInfos", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class OAuthServiceUserInfos : object
    {
        
        private string DataField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaypalSubStatus", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public enum PaypalSubStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscribed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivationKey", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class ActivationKey : object
    {
        
        private System.Nullable<System.DateTime> ActivationTimeField;
        
        private string CommentField;
        
        private System.DateTime CreationDateField;
        
        private bool DebugField;
        
        private int DurationInDaysField;
        
        private int DurationInMonthsField;
        
        private System.Guid IdField;
        
        private bool NewAccountOnlyField;
        
        private string OrderNumberField;
        
        private string PriceCurrencyField;
        
        private decimal PriceValField;
        
        private ServiceReference1.ActivationKeyType TypeField;
        
        private ServiceReference1.User UserField;
        
        private System.Nullable<System.Guid> UserIdField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActivationTime
        {
            get
            {
                return this.ActivationTimeField;
            }
            set
            {
                this.ActivationTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DurationInDays
        {
            get
            {
                return this.DurationInDaysField;
            }
            set
            {
                this.DurationInDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DurationInMonths
        {
            get
            {
                return this.DurationInMonthsField;
            }
            set
            {
                this.DurationInMonthsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NewAccountOnly
        {
            get
            {
                return this.NewAccountOnlyField;
            }
            set
            {
                this.NewAccountOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceCurrency
        {
            get
            {
                return this.PriceCurrencyField;
            }
            set
            {
                this.PriceCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceVal
        {
            get
            {
                return this.PriceValField;
            }
            set
            {
                this.PriceValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ActivationKeyType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class User : object
    {
        
        private System.DateTime CreationDateField;
        
        private ServiceReference1.Directory DirectoryField;
        
        private System.Guid DirectoryIdField;
        
        private string EmailField;
        
        private bool EmailConfirmedField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private bool IsDirectoryAdminField;
        
        private string LastNameField;
        
        private ServiceReference1.OAuth2Service OAuth2ServiceField;
        
        private string OAuth2ServiceUserIdField;
        
        private string PasswordHashField;
        
        private ServiceReference1.PaypalSubStatus PaypalSubStatusField;
        
        private System.Collections.Generic.List<ServiceReference1.UserPropertyValue> PropertyValuesField;
        
        private System.Collections.Generic.List<ServiceReference1.AccessToken> TokensField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Directory Directory
        {
            get
            {
                return this.DirectoryField;
            }
            set
            {
                this.DirectoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed
        {
            get
            {
                return this.EmailConfirmedField;
            }
            set
            {
                this.EmailConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDirectoryAdmin
        {
            get
            {
                return this.IsDirectoryAdminField;
            }
            set
            {
                this.IsDirectoryAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.OAuth2Service OAuth2Service
        {
            get
            {
                return this.OAuth2ServiceField;
            }
            set
            {
                this.OAuth2ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OAuth2ServiceUserId
        {
            get
            {
                return this.OAuth2ServiceUserIdField;
            }
            set
            {
                this.OAuth2ServiceUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash
        {
            get
            {
                return this.PasswordHashField;
            }
            set
            {
                this.PasswordHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PaypalSubStatus PaypalSubStatus
        {
            get
            {
                return this.PaypalSubStatusField;
            }
            set
            {
                this.PaypalSubStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.UserPropertyValue> PropertyValues
        {
            get
            {
                return this.PropertyValuesField;
            }
            set
            {
                this.PropertyValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.AccessToken> Tokens
        {
            get
            {
                return this.TokensField;
            }
            set
            {
                this.TokensField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivationKeyType", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public enum ActivationKeyType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnAirDirect = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aerosoft = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SimMarket = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SimWare = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Directory", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class Directory : object
    {
        
        private bool AutoValidateEmailField;
        
        private string ConfirmedEmailHtmlContentField;
        
        private string ForgetPasswordEmailHtmlContentField;
        
        private string ForgetPasswordEmailSubjectField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private string ValidationEmailFromEmailField;
        
        private string ValidationEmailHtmlContentField;
        
        private string ValidationEmailSubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoValidateEmail
        {
            get
            {
                return this.AutoValidateEmailField;
            }
            set
            {
                this.AutoValidateEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmedEmailHtmlContent
        {
            get
            {
                return this.ConfirmedEmailHtmlContentField;
            }
            set
            {
                this.ConfirmedEmailHtmlContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ForgetPasswordEmailHtmlContent
        {
            get
            {
                return this.ForgetPasswordEmailHtmlContentField;
            }
            set
            {
                this.ForgetPasswordEmailHtmlContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ForgetPasswordEmailSubject
        {
            get
            {
                return this.ForgetPasswordEmailSubjectField;
            }
            set
            {
                this.ForgetPasswordEmailSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationEmailFromEmail
        {
            get
            {
                return this.ValidationEmailFromEmailField;
            }
            set
            {
                this.ValidationEmailFromEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationEmailHtmlContent
        {
            get
            {
                return this.ValidationEmailHtmlContentField;
            }
            set
            {
                this.ValidationEmailHtmlContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationEmailSubject
        {
            get
            {
                return this.ValidationEmailSubjectField;
            }
            set
            {
                this.ValidationEmailSubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPropertyValue", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class UserPropertyValue : object
    {
        
        private System.Guid IdField;
        
        private ServiceReference1.User UserField;
        
        private System.Nullable<System.Guid> UserIdField;
        
        private ServiceReference1.UserProperty UserPropertyField;
        
        private System.Guid UserPropertyIdField;
        
        private System.Nullable<bool> ValueBoolField;
        
        private byte[] ValueBytesField;
        
        private System.Nullable<System.DateTime> ValueDateTimeField;
        
        private System.Nullable<double> ValueDoubleField;
        
        private string ValueFileExtField;
        
        private int ValueFileVersionField;
        
        private System.Nullable<int> ValueIntField;
        
        private string ValueStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.UserProperty UserProperty
        {
            get
            {
                return this.UserPropertyField;
            }
            set
            {
                this.UserPropertyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserPropertyId
        {
            get
            {
                return this.UserPropertyIdField;
            }
            set
            {
                this.UserPropertyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ValueBool
        {
            get
            {
                return this.ValueBoolField;
            }
            set
            {
                this.ValueBoolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ValueBytes
        {
            get
            {
                return this.ValueBytesField;
            }
            set
            {
                this.ValueBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValueDateTime
        {
            get
            {
                return this.ValueDateTimeField;
            }
            set
            {
                this.ValueDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueDouble
        {
            get
            {
                return this.ValueDoubleField;
            }
            set
            {
                this.ValueDoubleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueFileExt
        {
            get
            {
                return this.ValueFileExtField;
            }
            set
            {
                this.ValueFileExtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValueFileVersion
        {
            get
            {
                return this.ValueFileVersionField;
            }
            set
            {
                this.ValueFileVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ValueInt
        {
            get
            {
                return this.ValueIntField;
            }
            set
            {
                this.ValueIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueString
        {
            get
            {
                return this.ValueStringField;
            }
            set
            {
                this.ValueStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessToken", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class AccessToken : object
    {
        
        private System.DateTime ExpireDateField;
        
        private System.Guid IdField;
        
        private ServiceReference1.User UserField;
        
        private System.Guid UserIdField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireDate
        {
            get
            {
                return this.ExpireDateField;
            }
            set
            {
                this.ExpireDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProperty", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class UserProperty : object
    {
        
        private ServiceReference1.Directory DirectoryField;
        
        private System.Guid DirectoryIdField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private ServiceReference1.UserPropertyType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Directory Directory
        {
            get
            {
                return this.DirectoryField;
            }
            set
            {
                this.DirectoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DirectoryId
        {
            get
            {
                return this.DirectoryIdField;
            }
            set
            {
                this.DirectoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.UserPropertyType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPropertyType", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public enum UserPropertyType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bool = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bytes = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        File = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetPasswordParams", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class ResetPasswordParams : object
    {
        
        private string NewPasswordField;
        
        private System.Guid TokenIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TokenId
        {
            get
            {
                return this.TokenIdField;
            }
            set
            {
                this.TokenIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Server", Namespace="http://schemas.datacontract.org/2004/07/OnAir.Authentication")]
    public partial class Server : object
    {
        
        private System.Guid IdField;
        
        private string NameField;
        
        private string ServerHostnameField;
        
        private string WorldHostnameField;
        
        private System.Guid WorldIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerHostname
        {
            get
            {
                return this.ServerHostnameField;
            }
            set
            {
                this.ServerHostnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorldHostname
        {
            get
            {
                return this.WorldHostnameField;
            }
            set
            {
                this.WorldHostnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WorldId
        {
            get
            {
                return this.WorldIdField;
            }
            set
            {
                this.WorldIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOnAirAuthenticationWS")]
    public interface IOnAirAuthenticationWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/Register", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/RegisterResponse")]
        System.Threading.Tasks.Task<ServiceReference1.RegisterResult> RegisterAsync(ServiceReference1.RegisterParams register);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/Login", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.LoginResult> LoginAsync(ServiceReference1.LoginParams login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/UpdateUser", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/UpdateUserResponse")]
        System.Threading.Tasks.Task<ServiceReference1.WSResult> UpdateUserAsync(ServiceReference1.UpdateUserParams update);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/GetUserInfos", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/GetUserInfosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetUserInfosResult> GetUserInfosAsync(ServiceReference1.GetUserInfosParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/CheckAccessParams", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/CheckAccessParamsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.WSResult> CheckAccessParamsAsync(ServiceReference1.WSParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/GetUsers", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/GetUsersResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetUsersResult> GetUsersAsync(ServiceReference1.GetUsersParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/DeleteUser", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/DeleteUserResponse")]
        System.Threading.Tasks.Task<ServiceReference1.WSResult> DeleteUserAsync(ServiceReference1.DeleteUserParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/ForgetPassword", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/ForgetPasswordResponse")]
        System.Threading.Tasks.Task<ServiceReference1.WSResult> ForgetPasswordAsync(ServiceReference1.ForgetPasswordParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/ActivateKey", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/ActivateKeyResponse")]
        System.Threading.Tasks.Task<ServiceReference1.WSResult> ActivateKeyAsync(ServiceReference1.ActivateKeyParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/GetActivatedKeys", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/GetActivatedKeysResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetActivatedKeysResult> GetActivatedKeysAsync(ServiceReference1.WSParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/ResetPassword", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/ResetPasswordResponse")]
        System.Threading.Tasks.Task<ServiceReference1.WSResult> ResetPasswordAsync(ServiceReference1.ResetPasswordParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/GetSubscriptionEndDate", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/GetSubscriptionEndDateResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetSubscriptionEndDateResult> GetSubscriptionEndDateAsync(ServiceReference1.WSParams p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnAirAuthenticationWS/GetServers", ReplyAction="http://tempuri.org/IOnAirAuthenticationWS/GetServersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Server>> GetServersAsync(ServiceReference1.WSParams p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IOnAirAuthenticationWSChannel : ServiceReference1.IOnAirAuthenticationWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OnAirAuthenticationWSClient : System.ServiceModel.ClientBase<ServiceReference1.IOnAirAuthenticationWS>, ServiceReference1.IOnAirAuthenticationWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnAirAuthenticationWSClient() : 
                base(OnAirAuthenticationWSClient.GetDefaultBinding(), OnAirAuthenticationWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IOnAirAuthenticationWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnAirAuthenticationWSClient(EndpointConfiguration endpointConfiguration) : 
                base(OnAirAuthenticationWSClient.GetBindingForEndpoint(endpointConfiguration), OnAirAuthenticationWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnAirAuthenticationWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnAirAuthenticationWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnAirAuthenticationWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnAirAuthenticationWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnAirAuthenticationWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RegisterResult> RegisterAsync(ServiceReference1.RegisterParams register)
        {
            return base.Channel.RegisterAsync(register);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LoginResult> LoginAsync(ServiceReference1.LoginParams login)
        {
            return base.Channel.LoginAsync(login);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WSResult> UpdateUserAsync(ServiceReference1.UpdateUserParams update)
        {
            return base.Channel.UpdateUserAsync(update);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUserInfosResult> GetUserInfosAsync(ServiceReference1.GetUserInfosParams p)
        {
            return base.Channel.GetUserInfosAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WSResult> CheckAccessParamsAsync(ServiceReference1.WSParams p)
        {
            return base.Channel.CheckAccessParamsAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUsersResult> GetUsersAsync(ServiceReference1.GetUsersParams p)
        {
            return base.Channel.GetUsersAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WSResult> DeleteUserAsync(ServiceReference1.DeleteUserParams p)
        {
            return base.Channel.DeleteUserAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WSResult> ForgetPasswordAsync(ServiceReference1.ForgetPasswordParams p)
        {
            return base.Channel.ForgetPasswordAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WSResult> ActivateKeyAsync(ServiceReference1.ActivateKeyParams p)
        {
            return base.Channel.ActivateKeyAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetActivatedKeysResult> GetActivatedKeysAsync(ServiceReference1.WSParams p)
        {
            return base.Channel.GetActivatedKeysAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WSResult> ResetPasswordAsync(ServiceReference1.ResetPasswordParams p)
        {
            return base.Channel.ResetPasswordAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetSubscriptionEndDateResult> GetSubscriptionEndDateAsync(ServiceReference1.WSParams p)
        {
            return base.Channel.GetSubscriptionEndDateAsync(p);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Server>> GetServersAsync(ServiceReference1.WSParams p)
        {
            return base.Channel.GetServersAsync(p);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IOnAirAuthenticationWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IOnAirAuthenticationWS))
            {
                return new System.ServiceModel.EndpointAddress("https://auth.onair.company/WS/OnAirAuthenticationWS.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OnAirAuthenticationWSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IOnAirAuthenticationWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OnAirAuthenticationWSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IOnAirAuthenticationWS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IOnAirAuthenticationWS,
        }
    }
}
